import React from 'react';
import ReactDOM from "react-dom/client";
import './index.css';
import App from './App';
import './fonts/Nunito-Black.ttf';
import './fonts/Nunito-BlackItalic.ttf';
import './fonts/Nunito-Bold.ttf';
import './fonts/Nunito-BoldItalic.ttf';
import './fonts/Nunito-ExtraBold.ttf';
import './fonts/Nunito-ExtraBoldItalic.ttf';
import './fonts/Nunito-ExtraLight.ttf';
import './fonts/Nunito-ExtraLightItalic.ttf';
import './fonts/Nunito-Italic.ttf';
import './fonts/Nunito-Light.ttf';
import './fonts/Nunito-LightItalic.ttf';
import './fonts/Nunito-Medium.ttf';
import './fonts/Nunito-MediumItalic.ttf';
import './fonts/Nunito-Regular.ttf';
import './fonts/Nunito-SemiBold.ttf';
import './fonts/Nunito-SemiBoldItalic.ttf';

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<div id="topLevel"><App/></div>);